### PR TITLE
Switch to `quickbit-universal`

### PR DESCRIPTION
**Pull request by kasperisager**
~Still need to add~ indexing for maximum performance 🚀

### CODE REVIEW

**Comment by kasperisager** [comment]
@mafintosh I'll leave further optimisations for a separate PR so this should be ready for review.

**Comment by mafintosh** [comment]
@kasperisager good to go?

**Comment by kasperisager** [comment]
@mafintosh Yep, got indexing implemented for `lastIndexOf()` as well.

**Comment by mafintosh** [comment]
woot

**Comment by mafintosh** [comment]
Merged!

**Pull request merged**
