### PR TITLE
Accept an optional discoveryKey

### PR DESCRIPTION
**Pull request by javisantos**
I think is a good idea to have an optional discoveryKey

### CODE REVIEW

**Comment by javisantos** [comment]
What happens when 2 peers have the same discoveryKey for differents Keys?

**Comment by mafintosh** [comment]
Standard doesn't seem to like your test for some reason. Other than that I'm okay with making it configurable.

**Comment by martinheidegger** [comment]
@mafintosh seems like @javisantos pushed fixes.

**Comment by mafintosh** [comment]
Closing cause old and lots have changed (feel free to reopen again latest, feature makes sense)

**Pull request closed without merging**
